/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DbAuroraRouteImport } from './routes/db-aurora'
import { Route as IndexRouteImport } from './routes/index'

const DbAuroraRoute = DbAuroraRouteImport.update({
  id: '/db-aurora',
  path: '/db-aurora',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/db-aurora': typeof DbAuroraRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/db-aurora': typeof DbAuroraRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/db-aurora': typeof DbAuroraRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/db-aurora'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/db-aurora'
  id: '__root__' | '/' | '/db-aurora'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DbAuroraRoute: typeof DbAuroraRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/db-aurora': {
      id: '/db-aurora'
      path: '/db-aurora'
      fullPath: '/db-aurora'
      preLoaderRoute: typeof DbAuroraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DbAuroraRoute: DbAuroraRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
