minimumReleaseAge: 2880
minimumReleaseAgeStrict: true
minimumReleaseAgeExclude:
  - '@jaykingson/vite-plus-base'
  # Renovate security update: aws-cdk-lib@2.260.0
  - aws-cdk-lib@2.260.0

packages:
  - .
  - apps/*
  - packages/*
allowBuilds:
  esbuild: true
  msw: true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@1.0.0
  vite-plus: 1.0.0
  vitest: 5.0.3
overrides:
  vite@*: 'catalog:'
  vitest@*: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: '*'
