/**
 * Pulls the DS theme surface (tokens + dark semantic flip + gray bridge) out of
 * the vendored tanstack.com app.css so the app can load them without importing
 * the full marketing stylesheet (Tailwind twice, tw-fade, site chrome, etc.).
 *
 * Output lives outside the sync overwrite tree; sync regenerates it after copy.
 */

const GENERATED_BANNER = `/* AUTO-GENERATED by sync:tanstack-ds from src/webapp/ds/styles/app.css — do not edit.
 * Theme remap / fonts live in sibling files under src/webapp/styles/.
 */
`;

export const DS_TOKENS_GENERATED_REL = 'src/webapp/styles/ds-tokens.generated.css';

function extractBalancedBlock(css: string, openBraceIndex: number): string {
  if (css[openBraceIndex] !== '{') {
    throw new Error(`Expected '{' at index ${openBraceIndex}`);
  }
  let depth = 0;
  for (let i = openBraceIndex; i < css.length; i += 1) {
    const ch = css[i];
    if (ch === '{') {
      depth += 1;
    } else if (ch === '}') {
      depth -= 1;
      if (depth === 0) {
        return css.slice(openBraceIndex, i + 1);
      }
    }
  }
  throw new Error('Unbalanced `{` while extracting CSS block');
}

function extractRule(css: string, headerPattern: RegExp, label: string): string {
  const match = headerPattern.exec(css);
  if (!match || match.index === undefined) {
    throw new Error(`Missing required CSS block matching ${label}`);
  }
  const openBrace = css.indexOf('{', match.index);
  if (openBrace < 0) {
    throw new Error(`No '{' after block header matching ${label}`);
  }
  const block = extractBalancedBlock(css, openBrace);
  return `${css.slice(match.index, openBrace).trimEnd()} ${block}`;
}

export function extractDsThemeTokens(vendoredAppCss: string): string {
  const themeStatic = extractRule(vendoredAppCss, /@theme\s+static\b/, '@theme static');
  // First html.dark { … } is the semantic token flip (later ones are chrome/base).
  const htmlDark = extractRule(vendoredAppCss, /html\.dark(?=\s*\{)/, 'html.dark');
  const grayBridge = extractRule(vendoredAppCss, /:root\s*,\s*:host\b/, ':root, :host');

  if (!htmlDark.includes('--color-background-default')) {
    throw new Error('html.dark block did not include --color-background-default');
  }

  return [GENERATED_BANNER, themeStatic, '', grayBridge, '', htmlDark, '', ''].join('\n');
}
