name: Deploy Prod Stack

on:
  workflow_dispatch:

jobs:
  guard-main-ref:
    runs-on: ubuntu-latest
    steps:
      - name: Validate dispatch branch
        if: ${{ github.ref_name != 'main' }}
        run: |
          echo "Production deployment must be manually dispatched from the main branch."
          exit 1

  deploy-prod:
    needs: guard-main-ref
    uses: ./.github/workflows/_reusable-cdk-deploy.yml
    with:
      stage_source: prod
      lifecycle: permanent
      aws_region: ${{ vars.AWS_REGION || 'us-east-2' }}
    secrets:
      aws_role_to_assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
    environment: prod
    permissions:
      contents: read
      id-token: write
